export const PURE_MATH_2_CONTENT = `
# Pure Mathematics 2  
## 1. Proof
### 1.1 Mathematical Proof Structure
- A mathematical proof:
- Begins with given assumptions or axioms
- Proceeds through logical steps
- Reaches a valid conclusion
### 1.2 Proof by Exhaustion
- Definition:
- Testing all possible cases to demonstrate a statement is true
- Process:
- Identify the finite number of cases to be checked
- Verify each case individually
- Conclude the proof when all cases have been verified
- Example:
- To prove that x² - x + 41 is prime for 1 ≤ x ≤ 40:
- Substitute x = 1, 2, 3, ..., 40 into the formula
- Check that each resulting number is prime
### 1.3 Disproof by Counter-example
- Definition:
- Finding a single case where a statement is false to disprove it
- Process:
- Find one example that contradicts the claim
- The example must satisfy the conditions of the original statement
- This single case is sufficient to disprove the general statement
- Example:
- To disprove "n² - n + 41 is prime for all values of n":
- Try n = 41
- 41² - 41 + 41 = 1681 = 41 × 41
- Since 1681 is not prime, the statement is false
## 2. Algebra and Functions
### 2.1 Algebraic Division and Factor Theorem
- Polynomial Division:
- Dividing a polynomial f(x) by (ax + b) gives:
- f(x) = (ax + b) × q(x) + r
- Where q(x) is the quotient and r is the remainder
- Factor Theorem:
- If f(c) = 0, then (x - c) is a factor of f(x)
- Equivalently, if (ax + b) is a factor of f(x), then f(-b/a) = 0
- Remainder Theorem:
- When f(x) is divided by (x - a), the remainder equals f(a)
- Applications:
- Factorizing cubic polynomials like x³ + 3x² - 4 or 6x³ + 11x² - x - 6
- Finding the remainder when dividing by (ax + b)
## 3. Coordinate Geometry in the (x, y) Plane
### 3.1 Coordinate Geometry of the Circle
- Standard Form of Circle Equation:
- (x - a)² + (y - b)² = r²
- Center at (a, b) with radius r
- Circle Properties:
- The angle in a semicircle is a right angle
- If points A, B, and C lie on a circle and angle ABC = 90°, then AC is a diameter
- The perpendicular from the center to a chord bisects the chord
- If O is the center and OM ⊥ chord AB, then AM = MB
- A radius and a tangent at the point of contact are perpendicular
- If O is the center and P is a point on the circle, then OP ⊥ tangent at P
- Finding the Equation:
- Given the center (a, b) and radius r, the equation is (x - a)² + (y - b)² = r²
- Given the center (a, b) and a point (p, q) on the circle:
- r² = (p - a)² + (q - b)²
- Substitute into (x - a)² + (y - b)² = r²
## 4. Sequences and Series
### 4.1 Sequences
- Definition:
- A sequence is an ordered list of numbers that follow a pattern
- Types:
- Given by a formula for the nth term (e.g., aₙ = 2n + 3)
- Generated by a recurrence relation (e.g., xₙ₊₁ = 2xₙ + 1, x₁ = 3)
- Classifications:
- Increasing: Each term is greater than the previous
- Decreasing: Each term is less than the previous
- Periodic: The sequence repeats after a fixed number of terms
### 4.2 Arithmetic Sequences and Series
- Arithmetic Sequence:
- Consecutive terms differ by a constant value d (the common difference)
- nth term formula: aₙ = a₁ + (n - 1)d
- Where a₁ is the first term and d is the common difference
- Arithmetic Series:
- The sum of an arithmetic sequence
- Sum of n terms: Sₙ = n/2[2a₁ + (n - 1)d] = n/2(a₁ + aₙ)
- The sum of the first n natural numbers: Sₙ = n(n + 1)/2
- Proof of Sum Formula:
- For an arithmetic series with first term a and common difference d:
- Sₙ = a + (a + d) + (a + 2d) + ... + [a + (n-1)d]
- Sₙ = [a + (n-1)d] + [a + (n-2)d] + ... + a (writing in reverse)
- 2Sₙ = n[2a + (n-1)d]
- Sₙ = n/2[2a + (n-1)d]
### 4.3 Geometric Sequences and Series
- Geometric Sequence:
- Consecutive terms form a constant ratio r (the common ratio)
- nth term formula: aₙ = a₁ × r^(n-1)
- Where a₁ is the first term and r is the common ratio
- Geometric Series:
- The sum of a geometric sequence
- Sum of n terms: Sₙ = a₁(1 - r^n)/(1 - r), for r ≠ 1
- Sum to infinity (for |r| < 1): S∞ = a₁/(1 - r)
- Proof of Sum Formula:
- For a geometric series with first term a and common ratio r:
- Sₙ = a + ar + ar² + ... + ar^(n-1)
- rSₙ = ar + ar² + ... + ar^(n-1) + ar^n
- Sₙ - rSₙ = a - ar^n
- Sₙ(1 - r) = a(1 - r^n)
- Sₙ = a(1 - r^n)/(1 - r)
### 4.4 Binomial Expansion
- Expansion for Positive Integer n:
- (a + bx)ⁿ = aⁿ + (n₁)aⁿ⁻¹bx + (n₂)aⁿ⁻²b²x² + ... + bⁿxⁿ
- Where (nᵣ) = n!/(r!(n-r)!) is the binomial coefficient
- Also written as nCr or (nr)
- Notation:
- n! = n × (n-1) × (n-2) × ... × 3 × 2 × 1
- 0! = 1
## 5. Exponentials and Logarithms
### 5.1 Exponential Functions
- Function y = aˣ:
- a > 0, a ≠ 1
- Domain: All real numbers
- Range: All positive real numbers
- If a > 1: Strictly increasing function
- If 0 < a < 1: Strictly decreasing function
- Graph Characteristics:
- Passes through (0, 1)
- Asymptotic to the x-axis as x → -∞
- Grows without bound as x → ∞ (for a > 1)
### 5.2 Logarithms
- Definition:
- y = log_a(x) means aʸ = x, where a > 0, a ≠ 1, x > 0
- Laws of Logarithms:
- log_a(xy) = log_a(x) + log_a(y)
- log_a(x/y) = log_a(x) - log_a(y)
- log_a(xᵏ) = k log_a(x)
- log_a(1/x) = -log_a(x)
- log_a(a) = 1
- Natural Logarithm:
- log_e(x) is written as ln(x)
- Base e ≈ 2.71828...
### 5.3 Logarithmic Equations
- Solving aˣ = b:
- Take logarithms of both sides: x log(a) = log(b)
- Rearrange to find x: x = log(b)/log(a)
- Example:
- Solve 2ˣ = 5:
- Take log base 10 of both sides: log(2ˣ) = log(5)
- Use logarithm laws: x log(2) = log(5)
- Solve for x: x = log(5)/log(2) ≈ 2.32
## 6. Trigonometry
### 6.1 Trigonometric Relations
- Fundamental Identities:
- sin²θ + cos²θ = 1
- tanθ = sinθ/cosθ
- Applications:
- Used to simplify trigonometric expressions
- Useful in solving trigonometric equations
### 6.2 Trigonometric Equations
- Methods of Solution:
- Use of identities to simplify equations
- Factorization when possible
- Use of the quadratic formula for quadratic trigonometric equations
- Finding principal solutions and general solutions
- Examples:
- sin(x + π/3) = 1/2 for 0 < x < 2π
- cos(x + 30°) = 1/2 for -180° < x < 180°
- tan(2x) = 1 for 90° < x < 270°
- 6cos²x + sinx - 5 = 0 for 0 ≤ x < 360°
## 7. Differentiation
### 7.1 Applications of Differentiation
- Stationary Points:
- Points where the derivative equals zero: f'(x) = 0
- Types:
- Maximum: f'(x) = 0 and f''(x) < 0
- Minimum: f'(x) = 0 and f''(x) > 0
- Point of inflection: f'(x) = 0 and f''(x) = 0 (with sign change in f''(x))
- Increasing and Decreasing Functions:
- Increasing when f'(x) > 0
- Decreasing when f'(x) < 0
- Curve Sketching:
- Determine domain and range
- Find intercepts with axes
- Find stationary points
- Determine regions where function is increasing/decreasing
- Consider behavior as x → ±∞
## 8. Integration
### 8.1 Definite Integrals
- Definition:
- ∫_a^b f(x)dx represents the signed area between the curve y = f(x) and the x-axis from x = a to x = b
- Properties:
- ∫_a^b f(x)dx = F(b) - F(a), where F'(x) = f(x)
- ∫_a^b f(x)dx = -∫_b^a f(x)dx
- ∫_a^b [f(x) + g(x)]dx = ∫_a^b f(x)dx + ∫_a^b g(x)dx
### 8.2 Area Under a Curve
- Finding Areas:
- Area under curve y = f(x) from x = a to x = b: ∫_a^b f(x)dx
- Area between curve y = f(x) and line y = g(x): ∫_a^b [f(x) - g(x)]dx
- Area between two curves y = f(x) and y = g(x): ∫_a^b |f(x) - g(x)|dx
- Example:
- Area bounded by y = 6x - x² and y = 2x:
- Find intersection points by solving 6x - x² = 2x
- Simplify to x² - 4x = 0, giving x = 0 or x = 4
- Compute area: ∫_0^4 [(6x - x²) - 2x]dx = ∫_0^4 [4x - x²]dx
### 8.3 Trapezium Rule
- Formula:
- ∫_a^b f(x)dx ≈ (b-a)/2n [f(a) + 2f(x₁) + 2f(x₂) + ... + 2f(xₙ₋₁) + f(b)]
- Where x₁, x₂, ..., xₙ₋₁ are n-1 equally spaced points between a and b
- Process:
- Divide interval [a, b] into n equal strips of width h = (b-a)/n
- Calculate function values at all points
- Apply the formula to approximate the integral
- Accuracy:
- Generally improves as n increases
- Error estimation possible using calculus techniques

`;